### ISSUE TITLE
Hue motion sensor light (lux) very slow

### ISSUE THREAD

**Issue by sagitt** [azogue/fasthue#4]
Hi, integrations works fine for motion sensor, but light sensor (inside the motion sensor with temperature sensor too) is very slow.

if i turn on a light, the light level was updated after minutes.

there is a way to do it faster with this tool?

thanks.

**Comment by azogue** [comment]
It looks like the **internal** refresh rate for the light sensor in that device is of **~5 min**. 

The same applies to the temperature sensor, probably because it's a battery-powered device, in order to save energy, which is very reasonable.

**We cannot do anything about**, as this is a property of the device, and not related at all to the bridge polling. The bridge does not have a new value until the sensor sends an update. 

Not sure if there is any command in the Hue SDK to alter that refresh rate, but I imagine that is not possible, nor recommendable... sorry :(

Closing this one, as it cannot be fixed here.
