### ISSUE TITLE
Unable to add to integrations in UI

### ISSUE THREAD

**Issue by recklessnl** [azogue/fasthue#9]
Same problem as you have here: https://github.com/azogue/eventsensor/issues/12

Latest version of HASS, 0.111.3, and can't use either plugins because they don't show up in the integration UI list. Already rebooted, didn't work.

**Comment by azogue** [comment]
wow, that is very strange.

I suppose _something_ has changed _someplace_ in HA or HACS install process, because these issues look like only happen for new installs, right? (I updated to 111.2 and 111.3 without problems)

Does it happen **only** with my 2 integrations or with any HACS integration with UI config?

Also, have you checked that the code is present under the `/config/custom_components` folder? (I mean, let's first check that HACS is installing these CC's as expected, right?)

If it is present you could use the manual yaml config to start using them (yeah, sorry for that), as right now I have no idea of what is happening there. I'll try to find out, but with no time pressure :(

**Comment by mathieusibilla** [comment]
Hi, having a similar issue although the integration shows on the UI it doens tallow me to enter any interval? any ideas?
Home Assistant 0.113.2

**Comment by azogue** [comment]
Hi @mathieusibilla,

> Hi, having a similar issue although the integration shows on the UI it doens tallow me to enter any interval? any ideas?
Home Assistant 0.113.2

I don't understand what do you mean, don't you see something like this when adding the integration?
<img width="610" alt="fasthue_config_screen" src="https://user-images.githubusercontent.com/9748301/89730857-d5547480-da42-11ea-8e25-8095e6f3fd45.png">

After installed, you can change the interval anytime by using the newly available service (please read the docs).

As, anyway, this is not related to this issue, and the original one looks like it is not active again (and it was not related to the code in here), I'm closing this one.

Please open a new issue and describe your situation if it is not solved yet :)
